name: Basement work mode
entities:
  light.basement_office:
    brightness: 10
    friendly_name: Basement Office Lights
    state: 'on'
    supported_features: 1
  switch.basement_floor_lamp_gosund:
    friendly_name: Basement desk lamp
    icon: mdi:floor-lamp
    state: 'on'
