- alias: Turn on spare room light at night
  description: ''
  trigger:
  - at: '20:00:00'
    platform: time
  condition: []
  action:
  - domain: switch
    entity_id: switch.spare_room_lamp
    type: turn_on
  mode: single
