# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
homeassistant:
  customize: !include customize.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: https://3z3f9tm5v7iqev1px3n0t7xf2em28db8.ui.nabu.casa/

# Text to speech
tts:
  - platform: google_translate

frontend:
  themes: !include_dir_merge_named themes/

system_log:
  max_entries: 200

logger:
  default: info
  logs:
    homeassistant.components.ambient_station: debug
    aioambient: debug

recorder:
  purge_keep_days: 30

camera:

tuya: !include tuya.yaml

lovelace:
  mode: yaml

sensor:

remote_homeassistant: !include remote_homeassistant.yaml

ambient_station:
  api_key: !secret ambient_api_key
  app_key: !secret ambient_app_key_2

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
