- alias: Turn basement lamp on in the morning
  trigger:
  - platform: time
    at: 05:30
  action:
  - service: switch.turn_on
    entity_id: switch.basement_lamp

- alias: Turn basement lamp off in the morning
  trigger:
  - platform: sun
    event: sunrise
    offset: +00:30:00
  action:
  - service: switch.turn_off
    entity_id: switch.basement_lamp

- alias: Turn basement lamp on in the evening
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:00
  action:
  - service: switch.turn_on
    entity_id: switch.basement_lamp
  
- alias: Turn basement lamp off in the evening
  trigger:
  - platform: time
    at: '23:00'
  action:
  - entity_id: switch.basement_lamp
    service: switch.turn_off
